### ISSUE TITLE
Usage, character limits?

### ISSUE THREAD

**Issue by Geremia** [liraymond04/omegat-plugin-deepl-api-nokey#1]
What are the character or usage limits? For example, when I try to translate this segment:

>_Pénétré de pareilles idées, il n'avait pas à s'en tenir à la conception purement mécaniste de Descartes tendant à ne construire le monde qu'avec « de la ligure et du mouvement », vue trop simpliste aux yeux de Duhem pour qui statique mécanique et statique physico-chimique ne devaient former que deux chapitres particuliers d'une, doctrine plus compréhensive._

it gives a very incomplete/partial translation:

>For Duhem, mechanical statics and physico-chemical statics were just two specific chapters in a more comprehensive doctrine.

It does this [when I use DeepL.com](https://www.deepl.com/en/translator#fr/en-us/P%C3%A9n%C3%A9tr%C3%A9%20de%20pareilles%20id%C3%A9es%2C%20il%20n'avait%20pas%20%C3%A0%20s'en%20tenir%20%C3%A0%20la%20conception%20purement%20m%C3%A9caniste%20de%20Descartes%20tendant%20%C3%A0%20ne%20construire%20le%20monde%20qu'avec%20%C2%AB%20de%20la%20ligure%20et%20du%20mouvement%20%C2%BB%2C%20vue%20trop%20simpliste%20aux%20yeux%20de%20Duhem%20pour%20qui%20statique%20m%C3%A9canique%20et%20statique%20physico-chimique%20ne%20devaient%20former%20que%20deux%20chapitres%20particuliers%20d'une%2C%20doctrine%20plus%20compr%C3%A9hensive.), too, so it doesn't seem to be an issue with your plugin _per se_.

**Comment by liraymond04** [comment]
The character limit should be 2000, and I don't seem to run into any issues with Chinese text that goes up to 2000 characters both with the plugin and on the DeepL website. 

I'm not exactly sure why it's cutting short on this phrase, since even if there is no sentence splitting it should be nowhere near the limit. Is it like this for all other French text of similar or greater length?

**Comment by Geremia** [comment]
@liraymond04 

> I'm not exactly sure why it's cutting short on this phrase

This appears to be a DeepL issue for that particular segment. It handles French→English fairly well otherwise.

Also, I receive [HTTP error code 429 (too many requests)](https://http.dev/429) sometimes. Is there a way to bypass that, such as by passing my free DeepL account username/password to the plugin?

**Comment by Geremia** [comment]
> passing my free DeepL account username/password to the plugin

[omegat-plugin-deepl-api-free](https://github.com/ychoi-kr/omegat-plugin-deepl-api-free) allows using [DeepL API Free](https://www.deepl.com/en/pro/change-plan#developer) (500,000 chars/month) API key! 🤓
